name: Sync Fork

on:
  push:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull
        run: |
          git config --global user.email "EvanLuo42@users.noreply.github.com"
          git config --global user.name "EvanLuo42"
          git remote set-url origin https://${{secrets.PAT}}@github.com/CLCK0622/FRC-Wiki.git
          git push origin main
